version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: md-to-pdf
    versions:
    - 3.2.1
    - 3.3.0
    - 3.3.1
