name: Create PDF
on: push

jobs:
  lint:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          node -v
          npm ci
          node ./index.js
      - uses: actions/upload-artifact@v3
        with:
          name: create-pdf
          path: ./README.pdf
