name: Create PDF
on: [push]
jobs:
  create_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Create PDF
        uses: mkrakowitzer/actions-makepdfs@1.1
        with:
          markdown_dir: doc
          output_dir: pdf
